New folder/Github/force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New folder/Github/force-app/main/default/objects/Charge__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

New folder/Github/force-app/main/default/objects/Contact/fields/Card_Value__c.field-meta.xml
<CustomField>
    <fullName>Card_Value__c</fullName>
    <label>Card Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

New folder/Github/force-app/main/default/classes/HondaVehicleCharge.cls
public class HondaVehicleCharge {

    @AuraEnabled
    public static void chargeRecordCreation(Id recordId){
        Contact contact = [select FirstName,LastName from Contact where Id =: recordId];

        Charge__c charge = new Charge__c();
        charge.Contact_Id__c = recordId;
        charge.Start_Time__c = System.now();
        insert charge;
    }
    
    @AuraEnabled
    public static void updateEndTimeOnRelatedContact(Id recordId){
        Charge__c charge = [select id,Start_Time__c,End_Time__c,Contact_Id__c from Charge__c where Contact_Id__c =: recordId order by lastModifiedDate desc limit 1];
        charge.End_Time__c = System.now();
        update charge;
    }
    
    public static void sendEmailToContactwithChargingDetails(List<Contact> contactList){
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate template = [select id,subject,body,DeveloperName,HtmlValue from EmailTemplate where DeveloperName = 'Charging_Details'];
        for(Contact contact : contactList){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject(template.Subject);
            String body = template.HtmlValue;
            if(contact.FirstName != null){
                body = body.replace('[contactName]',String.valueOf(contact.FirstName));
            }
            if(contact.Card_Value__c != null){
                body = body.replace('[cardValue]',String.valueOf(contact.Card_Value__c));
            }
            mail.setHtmlBody(body);
            String []Address = new String[] { contact.Email };
            mail.settoAddresses(Address);
                mails.add(mail);
        }
        Messaging.sendEmail(mails);
    }
}